keycloak:
  extraArgs:
    - start
    - "--health-enabled=true"
    - "--hostname=auth-staging.rriv.org"
    - "--proxy-headers=xforwarded"
    - "--http-enabled=true"
    - "--hostname-strict=false"
  image:
    repository: quay.io/keycloak/keycloak
    tag: 26.0.7

webfingerDeployment:
  image: kleipper/rriv-webfinger-app:staging # TODO: put this in a rriv docker account

vault:
  address: "https://vault.staging.rriv.org:8200"