apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # The ACME server URL for Let's Encrypt
    server: {{ .Values.clusterIssuer.server }}  # e.g., https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.clusterIssuer.email }}
    privateKeySecretRef:
      name:  {{ .Values.clusterIssuer.privateKeySecretRef.name }}  # The Secret where the private key will be stored
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: {{ .Values.digitaloceanApiTokenSecret.name }}  # The Secret containing the DigitalOcean DNS API token
              key: {{ .Values.digitaloceanApiTokenSecret.key }}  # The key within the Secret that contains the API token
              namespace: {{ .Values.digitaloceanApiTokenSecret.namespace }}  # The namespace of the Secret
