apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    app: chirpstack-gateway-bridge
  name: chirpstack-gateway-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chirpstack-gateway-bridge
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        app: chirpstack-gateway-bridge
    spec:
      containers:
        - env:
            - name: INTEGRATION__MQTT__COMMAND_TOPIC_TEMPLATE
              value: us915/gateway/{{`{{ .GatewayID }}`}}/command/#
            - name: INTEGRATION__MQTT__EVENT_TOPIC_TEMPLATE
              value: 'us915/gateway/{{`{{ .GatewayID }}`}}/event/{{`{{ .EventType }}`}}'
            - name: INTEGRATION__MQTT__STATE_TOPIC_TEMPLATE
              value: 'us915/gateway/{{`{{ .GatewayID }}`}}/state/{{`{{ .StateType }}`}}'
          image: chirpstack/chirpstack-gateway-bridge:4
          name: chirpstack-gateway-bridge
          ports:
            - containerPort: 1700
              protocol: UDP
          volumeMounts:
            - mountPath: /etc/chirpstack-gateway-bridge
              name: chirpstack-gateway-bridge-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: chirpstack-gateway-bridge-cm0
          name: chirpstack-gateway-bridge-cm0
