digitaloceanApiTokenSecret:
  name: digitalocean-dns-api-key
  key: api-token
  namespace: cert-manager

certificate:
  name: rriv-dev-org-cert
  secretName: rriv-dev-org-tls
  dnsNames:
    - 'dev.rriv.org'
    - '*.dev.rriv.org'
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer

clusterIssuer:
  server: https://acme-v02.api.letsencrypt.org/directory 
  email: dev@rriv.org
  privateKeySecretRef:
    name: letsencrypt-account-key
  digitalocean:
    apiTokenSecretRef:
      name: digitalocean-dns-api-key
      key: api-token

externalSecret:
  secretStoreRef:
    name: cluster-secret-store
    namespace: external-secrets
    kind: ClusterSecretStore
    vault:
      server: https://vault.dev.rriv.org:8200
      path: "secret"
      version: v2
  doApiKey:
    name: digitalocean-dns-api-key
    namespace: cert-manager
    data:
      secretKey: api-token
      remoteRef:
        key: secret/digitalocean-dns-api-key
        property: api-token
  timescaleCreds:
    name: timescale-creds
    namespace: default
    data:
      secretKey: database_url
      remoteRef:
        key: secret/timescale-creds
        property: database_url

ingress:
  secretName: rriv-dev-org-tls
  hosts:
    keycloak: auth.dev.rriv.org
    vault: vault.dev.rriv.org
    chirpstack: chirp.dev.rriv.org
    chirpstackConsole: console-chirp.dev.rriv.org
    dataApi: api.dev.rriv.org
    webfinger: auth.dev.rriv.org

ingress-nginx:
  controller:
    enabled: true
    publishService:
      enabled: true
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/do-loadbalancer-name: "ingress-nginx-controller-dev"